library("devtools")
build()
install()
Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "/Users/alicia.koh/Downloads/hana_drivers")
conndec <- DatabaseConnector::createConnectionDetails(dbms = "hana", connectionString = "", user = "TENANT_WRITE_USER", password = "")
conn <- DatabaseConnector::connect(conndec)
DatabaseConnector::querySql(conn, "SELECT TOP 3 * FROM CDMSYNPUF1K.CONDITION_OCCURRENCE")